- hosts: localhost
  environment:
        PYTHONPATH: "/usr/local/lib/python3.6/site-packages/"
  tasks:
     - docker_container:
          name: "{{item.name}}" 

          image: "{{item.image}}"
          ports: 
           - "{{item.port}}:80"
          state: started
          privileged: yes
          ipc_mode: host
          interactive: true
          tty: true
          detach: true 
       with_items: 
          - { name: 'webserver1' , image: 'celebal:final1' , port: '8080' }
          - { name: 'webserver2' , image: 'celebal:final1' , port: '8081' }
          - { name: 'webserver3' , image: 'celebal:final1' , port: '8082' }
          - { name: 'load_balancer' , image: 'load_balancer:final' , port: 8083}
    
     
