- hosts: all
  tasks:
       - package: 
             name: git
             state: present
             enbled: true



- hosts: web_servers

  tasks:
       - package:
            name: httpd
            state: present
       - service:
            name: httpd
            state: started
            enabled: true

- hosts: load_balancer
 
  tasks:
      - package:
           name: nginx
           state: present
      - service:
           name: nginx
           state: present
           enabled: true
  
            
